/**
 * An implementation of an augmented interval tree in Grain.
 *
 * This tree is augmented with a random priority used to help maintain balance and a maxHigh field
 * used to optimize overlap queries.
 */
module IntervalTree

from "random" include Random
from "uint32" include Uint32

module Node {
  /** An interval node within the interval tree. */
  provide record rec Node<a> {
    /** The random generator used for assigning priorities */
    random: Random.Random,
    /** The interval of this node. */
    period: Range<a>,
    /** Randomly generated number between 10 and 100 */
    priority: Uint32,
    /** The highest endpoint in the subtree rooted at this node */
    maxHigh: a,
    /** The left child of this node */
    left: Option<Node<a>>,
    /** The right child of this node */
    right: Option<Node<a>>,
  }

  /**
   * Creates a new interval node with the given period and a random priority.
   *
   * Time Complexity: O(1)
   *
   * @param period: The interval to be stored in the node
   * @param random: The random generator used to assign a priority to the node
   *
   * @returns A new interval node with the specified period and a random priority
   */
  provide let make = (period: Range<a>, random: Random.Random) => {
    {
      random,
      period,
      // We generate a priority between 10 and 100, these numbers are somewhat random
      priority: Random.nextUint32InRange(random, 10ul, 100ul),
      maxHigh: period.rangeEnd,
      left: None,
      right: None,
    }
  }

  /**
   * Compares two nodes based on their intervals.
   *
   * @param currentPeriod: The period of the current node being compared
   * @param givenPeriod: The period to compare against
   *
   * @returns A positive value if the current node is greater than the given node, a negative value if the current node is less than the given node, or zero if they are equal
   */
  provide let compare = (currentPeriod: Range<a>, givenPeriod: Range<a>) => {
    let cmpStart = compare(currentPeriod.rangeStart, givenPeriod.rangeStart)
    let cmpEnd = compare(currentPeriod.rangeEnd, givenPeriod.rangeEnd)
    if (cmpStart == 0) cmpEnd else cmpStart
  }

  /**
   * Performs a left rotation on the given node.
   *
   * @param node: The node to rotate
   *
   * @returns The new root of the subtree after rotation
   *
   * @throws Failure(Message): If the given node has no right child, a left rotation cannot be performed and an error is thrown
   */
  provide let rotateLeft = (root: Node<a>) => {
    match (root) {
      { right: None, _ } =>
        fail "Cannot perform left rotation on a node with no right child",
      { right: Some({ left: childLeft, _ } as childNode), _ } => {
        { ...childNode, left: Some({ ...root, right: childLeft }) }
      },
    }
  }

  /**
   * Performs a right rotation on the given node.
   *
   * @param node: The node to rotate
   *
   * @returns The new root of the subtree after rotation
   *
   * @throws Failure(Message): If the given node has no left child, a right rotation cannot be performed and an error is thrown
   */
  provide let rotateRight = (node: Node<a>) => {
    match (node) {
      { left: None, _ } =>
        fail "Cannot perform right rotation on a node with no left child",
      { left: Some({ right: childRight, _ } as childNode), _ } => {
        { ...childNode, right: Some({ ...node, left: childRight }) }
      },
    }
  }

  /**
   * Sets the maxHigh interval to the maxHigh of the left and right children of the given nodes.
   *
   * @param node: The node to calculate the maxHigh for
   *
   * @returns The node with the maxHigh field updated to the maximum of its own maxHigh and the maxHigh of its children
   */
  provide let calculateMax = (node: Node<a>) => {
    let leftMax = match (node.left) {
      Some(leftNode) => leftNode.maxHigh,
      None => node.maxHigh,
    }
    let rightMax = match (node.right) {
      Some(rightNode) => rightNode.maxHigh,
      None => node.maxHigh,
    }
    use Pervasives.{ compare }
    let maxHigh = if (compare(leftMax, rightMax) > 0) leftMax else rightMax
    { ...node, maxHigh }
  }
}

/** An augmented interval tree. */
abstract record rec Tree<a> {
  random: Random.Random,
  /** The root node of the interval tree. */
  mut root: Option<Node.Node<a>>,
}

/**
 * Creates a new interval tree.
 *
 * @param seed: The seed for the random generator used to assign priorities to nodes in the tree
 *
 * @returns A new empty interval tree
 */
provide let make = seed => { random: Random.make(seed), root: None }

/**
 * Empties the given interval tree.
 *
 * @param self: The interval tree to be emptied
 */
provide let reset = self => self.root = None

/**
 * Checks if the given interval tree is empty
 *
 * @param self: The interval tree to be inspected
 *
 * @returns `true` if the tree is empty, `false` otherwise
 */
provide let isEmpty = self => {
  match (self.root) {
    Some(_) => false,
    None => true,
  }
}

/**
 * Returns the size of the given interval tree.
 *
 * @param self: The interval tree to inspect
 *
 * @returns The number of nodes in the tree
 */
provide let size = self => {
  let rec sizeHelp = (node: Node.Node<a>) => {
    match (node) {
      { left: None, right: None, _ } => 1,
      { left: Some(child), right: None, _ } => 1 + sizeHelp(child),
      { left: None, right: Some(child), _ } => 1 + sizeHelp(child),
      { left: Some(left), right: Some(right), _ } =>
        1 + sizeHelp(left) + sizeHelp(right),
    }
  }
  match (self.root) {
    Some(node) => sizeHelp(node),
    None => 0,
  }
}
/**
 * Adds a new interval to the tree.
 *
 * Time Complexity: O(log n)
 *
 * @param period: The interval to be added
 * @param self: The interval tree to which the interval will be added
 */
provide let add = (period: Range<a>, self: Tree<a>) => {
  // Create a new node for the given interval
  let newNode = Node.make(period, self.random)
  let rec addHelp = (newNode: Node.Node<a>, node: Node.Node<a>) => {
    // Binary Search based on low field
    let cmp = Node.compare(newNode.period, node.period)
    let node = if (cmp > 0) {
      // Go right or set right
      let node = match (node.right) {
        Some(childNode) =>
          { ...node, right: Some(addHelp(newNode, childNode)) },
        None => { ...node, right: Some(newNode) },
      }
      // Rotate if necessary
      use Uint32.{ (>) }
      match (node.right) {
        Some(childNode) when childNode.priority > node.priority =>
          Node.rotateLeft(node),
        _ => node,
      }
    } else if (cmp < 0) {
      // Go left or set left
      let node = match (node.left) {
        Some(childNode) => { ...node, left: Some(addHelp(newNode, childNode)) },
        None => { ...node, left: Some(newNode) },
      }
      // Rotate if necessary
      use Uint32.{ (>) }
      match (node.left) {
        Some(childNode) when childNode.priority > node.priority =>
          Node.rotateRight(node),
        _ => node,
      }
    } else {
      // If the intervals are equal we don't need to add it to the tree
      node
    }
    Node.calculateMax(node)
  }
  self.root = match (self.root) {
    Some(root) => Some(addHelp(newNode, root)),
    None => Some(newNode),
  }
}

/**
 * Removes a new interval from the tree.
 *
 * Time Complexity: O(log n)
 *
 * @param period: The interval to be removed
 * @param self: The interval tree of which the interval will be removed
 */
provide let remove = (period: Range<a>, self) => {
  let rec removeHelp = (period: Range<a>, node: Node.Node<a>) => {
    // Binary Search based on low field
    let cmp = Node.compare(period, node.period)
    let node = if (cmp < 0) {
      match (node.left) {
        Some(childNode) => { ...node, left: removeHelp(period, childNode) },
        None => node,
      }
    } else if (cmp > 0) {
      match (node.right) {
        Some(childNode) => { ...node, right: removeHelp(period, childNode) },
        None => node,
      }
    } else {
      let node = match (node) {
        { left: Some(left), right: None, _ } => Node.rotateRight(node),
        { left: None, right: Some(right), _ } => Node.rotateLeft(node),
        { left: Some(left), right: Some(right), _ } => {
          // Set the higher priority to the root
          use Uint32.{ (>) }
          if (left.priority > right.priority) {
            Node.rotateRight(node)
          } else {
            Node.rotateLeft(node)
          }
        },
        { left: None, right: None, _ } => return None,
      }
      match (removeHelp(period, node)) {
        Some(newNode) => newNode,
        None => return None,
      }
    }
    return Some(Node.calculateMax(node))
  }
  self.root = match (self.root) {
    Some(root) => removeHelp(period, root),
    None => None,
  }
}
/**
 * Checks if the tree contains a given interval.
 *
 * Time Complexity: O(log n)
 *
 * @param period: The interval to be checked for containment
 * @param self: The interval tree to be checked for containment
 *
 * @returns `true` if the tree contains the given interval, `false` otherwise
 */
provide let contains = (period: Range<a>, self) => {
  let rec containsHelp = (period: Range<a>, node: Node.Node<a>) => {
    let cmp = Node.compare(period, node.period)
    // Binary Search based on low field
    if (cmp == 0) {
      true
    } else if (cmp > 0) {
      match (node.right) {
        Some(childNode) => containsHelp(period, childNode),
        None => false,
      }
    } else {
      match (node.left) {
        Some(childNode) => containsHelp(period, childNode),
        None => false,
      }
    }
  }
  match (self.root) {
    Some(root) => containsHelp(period, root),
    None => false,
  }
}
/**
 * Finds an interval in the tree that overlaps with the given interval.
 *
 * @param period: The interval to be checked for overlap
 * @param self: The interval tree to be checked for overlap
 *
 * @returns Some(interval) if there is an overlapping interval in the tree, None otherwise
 */
provide let overlap = (period: Range<a>, self: Tree<a>) => {
  let mut curr = self.root
  while (true) {
    match (curr) {
      // Overlap condition: Two intervals [a, b] and [c, d] overlap if a <= d and c <= b
      Some(node) when node.period.rangeStart > period.rangeEnd
        || period.rangeStart > node.period.rangeEnd => {
        match (node.left) {
          Some(left) when period.rangeStart <= left.maxHigh => curr = node.left,
          _ => curr = node.right,
        }
      },
      _ => break,
    }
  }
  match (curr) {
    Some(node) => Some(node.period),
    None => None,
  }
}

/**
 * Prints the given tree in a human readable format.
 *
 * @param self: The tree to be printed
 */
provide let toString = self => {
  let rec toStringHelp = (node: Option<Node.Node<a>>, indent) => {
    match (node) {
      Some({ period, maxHigh, left, right, _ }) => {
        toStringHelp(right, indent ++ "         ")
          ++ (
            indent
            ++ "("
            ++ toString(period.rangeStart)
            ++ ", "
            ++ toString(period.rangeEnd)
            ++ ") "
            ++ toString(maxHigh)
            ++ "\n"
          )
          ++ toStringHelp(left, indent ++ "         ")
      },
      None when indent == "" => "Empty Tree\n",
      None => "",
    }
  }
  toStringHelp(self.root, "")
}
